const constants = {
  theme: ["theme-1", "theme-2"],
  selectedTheme: "themeThree",
  themeColor: "light-orange-theme",
  GA_MEASUREMENT_ID: process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID,
  themeObj: {
    themeOne: {
      listingPage: "grid-3",
      descriptionPage: "layoutOne",
      cartPage: "half",
      minicart: "dropdown",
    },
    themeTwo: {
      listingPage: "list",
      descriptionPage: "layoutTwo",
      cartPage: "full",
      minicart: "slider",
    },
    themeThree: {
      listingPage: [],
      descriptionPage: "layoutThree",
      cartPage: "half",
      minicart: "dropdown",
    },
  },
  // nodeUrl: "https://evheadless.dckap.co/api/graphql",
  // nodeUrl: "http://localhost:4000/graphql",
  // nodeUrl: "https://headlessdev.elementvape.com/api/",
  nodeUrl: process.env.NEXT_PUBLIC_BASE_URL,
  magentoBaseUrl: process.env.NEXT_PUBLIC_MAGENTO_BASE_URL,
  magnetoEndPointUrl: process.env.NEXT_PUBLIC_MAGENTO_GRAPHQL_ENDPOINT,
  HEADLESS_SOLUTION_THEME: 0,
  plpLayout: ["grid-2", "grid-3", "list"],
  YOTPO_INSTAGRAM_KEY: process.env.NEXT_PUBLIC_YOTPO_INSTAGRAM_KEY,
  YOTPO_REVIEWS_KEY: process.env.NEXT_PUBLIC_YOTPO_REVIEWS_KEY,
  NewArrivalsId: 17,
  showReviewWidgetURL: [
    "/coupons",
    "/about",
    "/reward-program",
    "/about",
    "/reviews",
    "/returns-policy",
  ],
  ACCEPT_JS_APP_LOGIN_ID: process.env.NEXT_PUBLIC_ACCEPT_JS_APP_LOGIN_ID,
  ACCEPT_JS_CLIENT_KEY: process.env.NEXT_PUBLIC_ACCEPT_JS_CLIENT_KEY,
  RECAPTCHA_KEY: process.env.NEXT_PUBLIC_RECAPTCHA_KEY,
  VAPID_KEY: process.env.NEXT_PUBLIC_VAPID_KEY,
  FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_MESSAGING_APP_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_APP_ID,
  FIREBASE_MESSAGING_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_MEASUREMENT_ID,
  replaceUrl: "https://www.elementvape.com",
  stagingReplaceUrl: "https://staging.elementvape.com",
  devReplaceUrl: "https://dev.elementvape.com/",
  adobeEndPointUrl: "https://catalog-service.adobe.io/graphql",
  magentoApiKey: process.env.NEXT_PUBLIC_MAGENTO_X_API_KEY,
  magentoEnvId: process.env.NEXT_PUBLIC_MAGENTO_ENV_ID,
  googleGtmId: process.env.NEXT_PUBLIC_GTM_ID,
};
export const magentoBaseUrl = process.env.NEXT_PUBLIC_MAGENTO_BASE_URL;
export default constants;
